name = "Forge Pony"
author = "Sky Splash"
version = "1.4.3-1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c64f235174d5e5b125af440ce0c14432623b260a827f064b72ec69f711fdb561"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["1.21"]
