name = "Forge Pony"
author = "Sky Splash"
version = "0.1.0-1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f036e095711d83ba2b30cadbfd4025a6faba2b4c1313cc76b614565cf3f0d051"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.46"

[options]
acceptable-game-versions = ["1.21"]
