name = "Forge Pony"
author = "Sky Splash"
version = "1.4.4-1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e0f2610a394d691993a1bd15573b4dd5161916c54098e1335364521a75d3602"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21"]
