name = "Forge Pony"
author = "Sky Splash"
version = "0.1.1-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7361582b1a7ea2bfe395a99a9ba832431235b0347e75aa5b26939c47612813c4"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
acceptable-game-versions = ["1.20"]
