name = "Forge Pony"
author = "Sky Splash"
version = "1.3.3-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f3ce4dbe388c57e3f5282249844bcba527483d8e7ca122f9c8b717e4080c627"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
