name = "Forge Pony"
author = "Sky Splash"
version = "1.3.4-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3897ff9fb7f15166ad0a8fbefa4793dfd64fbf444aba63b5fd396c63ad378d3d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
