name = "Forge Pony"
author = "Sky Splash"
version = "1.3.2-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c477a9873c7532673c7c355ba664b11e388a86d50899fb189a09af016539f48"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
